### ISSUE TITLE
Compiling with intel/17.0.4 and impi/17.3

### ISSUE THREAD

**Issue by aldubois** [kabicm/grid2grid#10]
Hi,

I run into a minor error while trying to compile with  intel/17.0.4 and impi/17.3:

```
grid2grid/src/grid2grid/comm_volume.hpp(116): error: no suitable user-defined conversion from "grid2grid::comm_volume::volume_t" to "grid2grid::comm_volume" exists
          return sum_comm_vol;
```

There is also a problem in the `transform_test.cpp` test (most likely the test is partially commented/outdated).

**Comment by kabicm** [comment]
Hi @aldubois! Your PR has been approved now. It seems you are right regarding the `transform_test.cpp`, but I will investigate it soon.
